services:
  django: &django
    image: {{ cookiecutter.project_slug }}:latest
    ports:
      - "8000:8000"
    volumes:
      - app_data:/data
    depends_on:
      - database
      - valkey
      - mailpit
    environment:
      - DEBUG=True
    env_file: .env.compose

  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file: .env.compose
    volumes:
      - database_data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:latest
    environment:
      VALKEY_EXTRA_FLAGS: '--save 60 1 --loglevel warning'
    ports:
      - 6379:6379
    volumes:
      - valkey_data:/data

  mailpit:
    image: docker.io/axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    env_file: .env.compose

  celeryworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}_worker
    depends_on:
      - valkey
      - database
      - mailpit
    ports: []
    command: worker

   celerybeat:
    <<: *django
    image: {{ cookiecutter.project_slug }}_celerybeat
    depends_on:
      - valkey
      - database
      - mailpit
    ports: []
    command: beat

  flower:
    <<: *django
    image: {{ cookiecutter.project_slug }}_flower
    ports:
      - '5555:5555'
    command: 'flower'




volumes:
  app_data:
  database_data:
  valkey_data:
